=== jijilak/ITMO.HTML.XML.Course/XML/lessons_DTD.dtd
<!ELEMENT schedule (item+)>
	
	<ELEMENT discipline id = "a"(Name, MiddleName, LastName, Lesson, Post, DateLessons, Address, NumberOfHours, FinalGrade)>
	<!ELEMENT Name (#PCDATA)>
	<!ELEMENT MiddleName (#PCDATA)>
	<!ELEMENT LastName (#PCDATA)>
	<!ELEMENT Lesson (#PCDATA)>
	<!ELEMENT Post (#PCDATA)>
	<!ELEMENT DateLessons (#PCDATA)>
	<!ELEMENT Address (#PCDATA)>
	<!ELEMENT NumberOfHours (#PCDATA)>
	<!ELEMENT FinalGrade (#PCDATA)>
	
	<ELEMENT discipline id = "b"(Name, MiddleName, LastName, Lesson, Post, DateLessons, Address, NumberOfHours, FinalGrade)>
	<!ELEMENT Name (#PCDATA)> 
	<!ELEMENT MiddleName (#PCDATA)>
	<!ELEMENT LastName (#PCDATA)>
	<!ELEMENT Lesson (#PCDATA)>
	<!ELEMENT Post (#PCDATA)>
	<!ELEMENT DateLessons (#PCDATA)>
	<!ELEMENT Address (#PCDATA)>
	<!ELEMENT NumberOfHours (#PCDATA)>
	<!ELEMENT FinalGrade (#PCDATA)>
	
	<ELEMENT discipline id = "c"(Name, MiddleName, LastName, Lesson, Post, DateLessons, Address, NumberOfHours, FinalGrade)>
	<!ELEMENT Name (#PCDATA)> 
	<!ELEMENT MiddleName (#PCDATA)>
	<!ELEMENT LastName (#PCDATA)>
	<!ELEMENT Lesson (#PCDATA)>
	<!ELEMENT Post (#PCDATA)>
	<!ELEMENT DateLessons (#PCDATA)>
	<!ELEMENT Address (#PCDATA)>
	<!ELEMENT NumberOfHours (#PCDATA)>
	<!ELEMENT FinalGrade (#PCDATA)>
	
	<ELEMENT discipline id = "d"(Name, MiddleName, LastName, Lesson, Post, DateLessons, Address, NumberOfHours, FinalGrade)>
	<!ELEMENT Name (#PCDATA)> 
	<!ELEMENT MiddleName (#PCDATA)>
	<!ELEMENT LastName (#PCDATA)>
	<!ELEMENT Lesson (#PCDATA)>
	<!ELEMENT Post (#PCDATA)>
	<!ELEMENT DateLessons (#PCDATA)>
	<!ELEMENT Address (#PCDATA)>
	<!ELEMENT NumberOfHours (#PCDATA)>
	<!ELEMENT FinalGrade (#PCDATA)>

=== jijilak/ITMO.HTML.XML.Course/XML/lessons.xml
<?xml version = "1.0"?>
<!DOCTYPE schedule SYSTEM "lessons_DTD.dtd">
<schedule>
	<discipline id = "a">
	<Name>Никита</Name>
		<MiddleName>Алексеевич</MiddleName>
		<LastName>Осипов</LastName>
		<Lesson>"Технологии программирования"</Lesson>
		<Post>преподаватель доцент</Post>
		<DateLessons>27, 28, 30.09, 01, 04, 07, 11, 12, 14.10</DateLessons>
		<Address>online</Address>
		<NumberOfHours>45</NumberOfHours>
		<FinalGrade>зачёт</FinalGrade>
	</discipline>
<discipline id = "b">
		<Name>Денис</Name>
		<MiddleName>Викторович</MiddleName>
		<LastName>Ямщиков</LastName>
		<Lesson>"Введение в базы данных"</Lesson>
		<Post>старший преподаватель</Post>
		<DateLessons>18, 19, 21, 22, 25, 26.10</DateLessons>
		<Address>online</Address>
		<NumberOfHours>30</NumberOfHours>
		<FinalGrade>зачёт</FinalGrade>
	</discipline>
	<discipline id = "c">
		<Name>Олег</Name>
		<MiddleName>Александрович</MiddleName>
		<LastName>Третьяков</LastName>
		<Lesson>"Программирование на C#"</Lesson>
		<Post>старший преподаватель</Post>
		<DateLessons>02, 03, 09, 10, 12, 16, 17, 19, 23, 24.11</DateLessons>
		<Address>online</Address>
		<NumberOfHours>30</NumberOfHours>
		<FinalGrade>зачёт</FinalGrade>
	</discipline>
		<discipline id = "d">
		<Name>Денис</Name>
		<MiddleName>Викторович</MiddleName>
		<LastName>Ямщиков</LastName>
		<Lesson>"Transact-SQL и Разработка Microsoft SQL Server"</Lesson>
		<Post>старший преподаватель</Post>
		<DateLessons>02-28.12</DateLessons>
		<Address>online</Address>
		<NumberOfHours>65</NumberOfHours>
		<FinalGrade>экзамен</FinalGrade>
	</discipline>
</schedule>
